import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, BookOpen, Crown, FlaskConical, MessagesSquare, Skull, Swords, Compass } from 'lucide-react';
import heroImage from '@/assets/medieval-kingdom.jpg';
import questsImage from '@/assets/medieval-quests.jpg';
import { ALL_LESSONS } from '@/data/curriculum';
import { LABS } from '@/data/labs';
import { BOSSES } from '@/data/challenges';
import { REGIONS } from '@/data/world';
import { useAuth } from '@/lib/auth';
import { useI18n } from '@/lib/i18n';
import { LanguageSwitcher } from '@/components/LanguageSwitcher';
import { Button } from '@/components/ui/button';
import { RealmAtlas } from '@/components/RealmAtlas';
const copy = {
 pt: {kicker:'UMA NOVA JORNADA COMEÇA',title:'Seu próximo nível é lendário.',lead:'Do primeiro comando ao domínio da cloud. Explore reinos, conquiste habilidades e escreva sua história em DevOps.',explore:'Explorar a jornada',world:'Um mundo inteiro para conquistar.',worldLead:'Cada reino, uma nova habilidade. Seu caminho do zero ao Ninja.',quests:'Escolha sua próxima missão.',questsLead:'Conhecimento é a sua arma. A prática, a sua aventura.',learn:'Biblioteca dos saberes',forge:'Forja de habilidades',battle:'Arena dos dragões',learnDesc:'Linux, Git, cloud e muito mais. Uma conquista de cada vez.',forgeDesc:'Transforme a teoria em experiência com laboratórios reais.',battleDesc:'Encare os chefes de produção e prove suas habilidades.',guild:'A aventura é melhor em uma guilda.',guildLead:'Compartilhe descobertas, tire dúvidas e evolua com outros aventureiros.',join:'Entrar na comunidade',end:'Todo Ninja começou no nível 1.',endLead:'Sua primeira missão está esperando por você.'},
 en: {kicker:'A NEW JOURNEY BEGINS',title:'Your next level is legendary.',lead:'From your first command to mastering the cloud. Explore realms, conquer skills and write your own DevOps story.',explore:'Explore the journey',world:'A whole world to conquer.',worldLead:'Every realm, a new skill. Your path from zero to Ninja.',quests:'Choose your next quest.',questsLead:'Knowledge is your weapon. Practice is your adventure.',learn:'Library of knowledge',forge:'Forge of skills',battle:'Dragon arena',learnDesc:'Linux, Git, cloud and more. One achievement at a time.',forgeDesc:'Turn theory into experience with real laboratories.',battleDesc:'Face production bosses and prove your skills.',guild:'Adventure is better with a guild.',guildLead:'Share discoveries, ask questions and grow with fellow adventurers.',join:'Join the community',end:'Every Ninja started at level 1.',endLead:'Your first quest is waiting for you.'},
 es: {kicker:'COMIENZA UNA NUEVA AVENTURA',title:'Tu próximo nivel es legendario.',lead:'De tu primer comando al dominio de la cloud. Explora reinos, conquista habilidades y escribe tu historia en DevOps.',explore:'Explorar la aventura',world:'Todo un mundo por conquistar.',worldLead:'Cada reino, una nueva habilidad. Tu camino de cero a Ninja.',quests:'Elige tu próxima misión.',questsLead:'El conocimiento es tu arma. La práctica, tu aventura.',learn:'Biblioteca del saber',forge:'Forja de habilidades',battle:'Arena de dragones',learnDesc:'Linux, Git, cloud y mucho más. Una conquista a la vez.',forgeDesc:'Convierte la teoría en experiencia con laboratorios reales.',battleDesc:'Enfréntate a los jefes de producción y demuestra tus habilidades.',guild:'La aventura es mejor con un gremio.',guildLead:'Comparte descubrimientos, resuelve dudas y crece con otros aventureros.',join:'Entrar en la comunidad',end:'Todo Ninja empezó en el nivel 1.',endLead:'Tu primera misión te está esperando.'}
};
export const Route = createFileRoute('/')({head: () => ({meta:[{title:'DevOpsQuest — sua aventura do zero ao Ninja'},{name:'description',content:'Aprenda DevOps em uma aventura RPG: aulas completas, laboratórios, reinos, desafios e comunidade em português, espanhol e inglês.'},{property:'og:title',content:'DevOpsQuest — sua aventura do zero ao Ninja'},{property:'og:description',content:'Explore reinos e conquiste habilidades reais de DevOps, do primeiro comando ao nível Ninja.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Landing});
function Landing() {
 const {t,lang} = useI18n(); const {session} = useAuth(); const c = copy[lang];
 const activities = [{to:'/modulos',icon:BookOpen,title:c.learn,description:c.learnDesc},{to:'/laboratorios',icon:FlaskConical,title:c.forge,description:c.forgeDesc},{to:'/boss-battles',icon:Skull,title:c.battle,description:c.battleDesc}] as const;
 return <div className="medieval-landing">
  <header className="landing-nav"><div className="mx-auto flex max-w-7xl items-center gap-4 px-5 py-4 lg:px-8">
   <Link to="/" className="flex min-w-0 items-center gap-3"><span className="brand-crest"><Swords /></span><span className="font-display text-lg font-extrabold sm:text-xl">DevOps<span className="text-primary">Quest</span></span></Link>
   <nav className="ml-10 hidden items-center gap-7 text-sm text-muted-foreground lg:flex" aria-label={t('nav.aria')}><Link to="/mapa">{t('nav.map')}</Link><Link to="/modulos">{t('nav.modules')}</Link><Link to="/comunidade">{t('nav.community')}</Link></nav>
   <div className="ml-auto flex items-center gap-3"><LanguageSwitcher /><Button asChild variant="outline" className="nav-login"><Link to={session ? '/dashboard' : '/auth'}>{session ? t('rpg.ctaContinue') : t('shell.signIn')}<ArrowRight className="hidden sm:block" /></Link></Button></div>
  </div></header>
  <main>
   <section className="adventure-hero">
    <img src={heroImage} width={1920} height={1024} alt="" className="hero-art" />
    <div className="hero-shade" />
    <div className="hero-copy mx-auto w-full max-w-7xl px-5 lg:px-8"><p className="hero-kicker"><span />{c.kicker}</p><h1>DevOps<span>Quest</span></h1><h2>{c.title}</h2><p className="hero-lead">{c.lead}</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild size="lg" className="adventure-cta"><Link to={session ? '/dashboard' : '/auth'} search={session ? {} : {mode:'signup'}}><Swords />{session ? t('rpg.ctaContinue') : t('rpg.ctaCreate')}</Link></Button><Button asChild variant="outline" size="lg" className="adventure-secondary"><Link to="/mapa"><Compass />{c.explore}</Link></Button></div><p className="mt-5 text-xs text-hero-muted">{t('rpg.badgeLangs')}</p></div>
    <span className="hero-coordinate" aria-hidden>◆ DEVOPSQUEST · I</span>
   </section>
   <section className="campaign-stats"><div className="mx-auto grid max-w-7xl grid-cols-2 px-5 sm:grid-cols-4 lg:px-8">{[{icon:Crown,value:REGIONS.length,label:t('rpg.hudRealms')},{icon:BookOpen,value:ALL_LESSONS.length,label:t('rpg.hudQuests')},{icon:FlaskConical,value:LABS.length,label:t('rpg.hudLabs')},{icon:Skull,value:BOSSES.length,label:t('rpg.hudBosses')}].map(({icon:Icon,value,label})=><div key={label} className="campaign-stat"><Icon /><strong>{value}</strong><span>{label}</span></div>)}</div></section>
   <section className="adventure-section mx-auto max-w-7xl px-5 lg:px-8"><div className="section-heading"><span className="section-symbol"><Compass /></span><p className="section-kicker">{t('rpg.mapTitle')}</p><h2>{c.world}</h2><p>{c.worldLead}</p></div><RealmAtlas /></section>
   <section className="quest-section"><div className="adventure-section mx-auto max-w-7xl px-5 lg:px-8"><div className="section-heading"><span className="section-symbol"><Swords /></span><p className="section-kicker">{t('rpg.hudQuests')}</p><h2>{c.quests}</h2><p>{c.questsLead}</p></div><div className="quest-grid">{activities.map(({to,icon:Icon,title,description},i)=><Link to={to} className="quest-card group" key={to}><div className={`quest-art quest-art-${i}`}><img src={questsImage} width={1536} height={768} loading="lazy" alt="" /></div><div className="quest-body"><span className="quest-category"><Icon />0{i+1}</span><h3>{title}</h3><p>{description}</p><span className="quest-arrow"><ArrowRight /></span></div></Link>)}</div></div></section>
   <section className="guild-section mx-auto grid max-w-7xl items-center gap-8 px-5 lg:grid-cols-[auto_1fr_auto] lg:px-8"><div className="guild-emblem"><MessagesSquare /></div><div><p className="section-kicker">{t('nav.community')}</p><h2>{c.guild}</h2><p className="mt-3 max-w-xl text-sm text-muted-foreground">{c.guildLead}</p></div><Button asChild variant="outline" size="lg"><Link to="/comunidade">{c.join}<ArrowRight /></Link></Button></section>
   <section className="final-adventure"><Crown className="mx-auto mb-5 size-8 text-primary" /><h2>{c.end}</h2><p className="mt-3 text-muted-foreground">{c.endLead}</p><Button asChild size="lg" className="mt-7 adventure-cta"><Link to={session ? '/dashboard' : '/auth'} search={session ? {} : {mode:'signup'}}><Swords />{session ? t('rpg.ctaContinue') : t('rpg.ctaCreate')}</Link></Button><div className="mt-8 flex justify-center"><LanguageSwitcher variant="full" /></div></section>
  </main>
  <footer className="landing-footer"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 lg:px-8"><Link to="/" className="flex items-center gap-2 font-display font-bold"><Swords className="size-4 text-primary" />DevOpsQuest</Link><span className="text-xs text-muted-foreground">{t('shell.footer')}</span><div className="flex gap-5 text-xs text-muted-foreground"><Link to="/termos">{t('legal.terms.title')}</Link><Link to="/privacidade">{t('legal.privacy.title')}</Link></div></div></footer>
 </div>;
}
