/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ModulosIndexRouteImport } from './routes/modulos.index'
import { Route as ModulosSlugRouteImport } from './routes/modulos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosIndexRoute = ModulosIndexRouteImport.update({
  id: '/modulos/',
  path: '/modulos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosSlugRoute = ModulosSlugRouteImport.update({
  id: '/modulos/$slug',
  path: '/modulos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/skills': typeof SkillsRoute
  '/modulos/$slug': typeof ModulosSlugRoute
  '/modulos/': typeof ModulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/skills': typeof SkillsRoute
  '/modulos/$slug': typeof ModulosSlugRoute
  '/modulos': typeof ModulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapa': typeof MapaRoute
  '/skills': typeof SkillsRoute
  '/modulos/$slug': typeof ModulosSlugRoute
  '/modulos/': typeof ModulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mapa' | '/skills' | '/modulos/$slug' | '/modulos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mapa' | '/skills' | '/modulos/$slug' | '/modulos'
  id: '__root__' | '/' | '/mapa' | '/skills' | '/modulos/$slug' | '/modulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapaRoute: typeof MapaRoute
  SkillsRoute: typeof SkillsRoute
  ModulosSlugRoute: typeof ModulosSlugRoute
  ModulosIndexRoute: typeof ModulosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/': {
      id: '/modulos/'
      path: '/modulos'
      fullPath: '/modulos/'
      preLoaderRoute: typeof ModulosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/$slug': {
      id: '/modulos/$slug'
      path: '/modulos/$slug'
      fullPath: '/modulos/$slug'
      preLoaderRoute: typeof ModulosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapaRoute: MapaRoute,
  SkillsRoute: SkillsRoute,
  ModulosSlugRoute: ModulosSlugRoute,
  ModulosIndexRoute: ModulosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
